apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # This key must match the $oidc.keycloak.clientSecret reference in argocd-cm
  oidc.keycloak.clientSecret: "PUT_YOUR_KEYCLOAK_CLIENT_SECRET_HERE"
