apiVersion: v1
kind: Namespace
metadata:
  name: shopverse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: shopverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: vignesh8386/api-gateway:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: shopverse-config
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: vignesh8386/user-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: '3001'
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_USER
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shopverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: vignesh8386/authentication-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: '3002'
        - name: JWT_SECRET
          value: supersecretjwtkey_12345
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_AUTH
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: vignesh8386/product-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: '3003'
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_PRODUCT
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: vignesh8386/search-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: '3004'
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_SEARCH
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: vignesh8386/inventory-service:latest
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: '3005'
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_INVENTORY
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: vignesh8386/cart-service:latest
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: '3006'
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: INVENTORY_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_CART
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
      - name: wishlist-service
        image: vignesh8386/wishlist-service:latest
        ports:
        - containerPort: 3007
        env:
        - name: PORT
          value: '3007'
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_WISHLIST
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vignesh8386/order-service:latest
        ports:
        - containerPort: 3008
        env:
        - name: PORT
          value: '3008'
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_ORDER
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: vignesh8386/payment-service:latest
        ports:
        - containerPort: 3009
        env:
        - name: PORT
          value: '3009'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: ORDER_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_PAYMENT
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
      - name: invoice-service
        image: vignesh8386/invoice-service:latest
        ports:
        - containerPort: 3010
        env:
        - name: PORT
          value: '3010'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: ORDER_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PAYMENT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_INVOICE
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: vignesh8386/shipping-service:latest
        ports:
        - containerPort: 3011
        env:
        - name: PORT
          value: '3011'
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: ORDER_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_SHIPPING
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-rating-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-rating-service
  template:
    metadata:
      labels:
        app: review-rating-service
    spec:
      containers:
      - name: review-rating-service
        image: vignesh8386/review-rating-service:latest
        ports:
        - containerPort: 3012
        env:
        - name: PORT
          value: '3012'
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_REVIEW
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: vignesh8386/recommendation-service:latest
        ports:
        - containerPort: 3013
        env:
        - name: PORT
          value: '3013'
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: ORDER_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_RECOMMENDATION
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: vignesh8386/admin-service:latest
        ports:
        - containerPort: 3014
        env:
        - name: PORT
          value: '3014'
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: USER_SERVICE_URL
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: PRODUCT_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: ORDER_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: INVENTORY_SERVICE_URL
        - name: SHIPPING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: SHIPPING_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: shopverse-config
              key: MONGO_URI_ADMIN
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: shopverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: vignesh8386/frontend-ui:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
